/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#f8faf8",
        "inverse-on-surface": "#eff1ef",
        "secondary-container": "#fdc003",
        "on-background": "#191c1b",
        "on-secondary-fixed": "#261a00",
        "outline-variant": "#c3c8c1",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#6c5000",
        "inverse-primary": "#b4cdb8",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#404754",
        "surface-container-highest": "#e1e3e1",
        "on-tertiary-container": "#8c93a2",
        "on-surface-variant": "#434843",
        "secondary-fixed": "#ffdf9e",
        "outline": "#737973",
        "surface-variant": "#e1e3e1",
        "on-error-container": "#93000a",
        "secondary": "#785900",
        "tertiary": "#101823",
        "primary-container": "#1b3022",
        "surface-tint": "#4d6453",
        "tertiary-container": "#252c38",
        "on-primary-container": "#819986",
        "inverse-surface": "#2e3130",
        "primary-fixed-dim": "#b4cdb8",
        "tertiary-fixed-dim": "#c0c7d6",
        "secondary-fixed-dim": "#fabd00",
        "on-secondary-fixed-variant": "#5b4300",
        "background": "#f8faf8",
        "on-primary-fixed": "#0b2013",
        "error-container": "#ffdad6",
        "surface-container": "#eceeec",
        "surface-container-low": "#f2f4f2",
        "on-surface": "#191c1b",
        "on-tertiary": "#ffffff",
        "primary": "#061b0e",
        "surface-dim": "#d8dad9",
        "error": "#ba1a1a",
        "primary-fixed": "#d0e9d4",
        "tertiary-fixed": "#dce2f3",
        "surface-container-high": "#e6e9e7",
        "on-primary-fixed-variant": "#364c3c",
        "surface-bright": "#f8faf8",
        "on-tertiary-fixed": "#151c27"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1280px",
        "section-gap": "80px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        "base": "8px",
        "gutter": "24px"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "body-sm": ["Inter"],
        "data-mono": ["Inter"],
        "label-caps": ["Inter"],
        "headline-md": ["Playfair Display"],
        "headline-xl": ["Playfair Display"],
        "body-md": ["Inter"],
        "headline-sm": ["Playfair Display"],
        "headline-lg": ["Playfair Display"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "data-mono": ["16px", {"lineHeight": "24px", "letterSpacing": "-0.01em", "fontWeight": "500"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "600"}],
        "headline-md": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
        "headline-xl": ["64px", {"lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-sm": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-lg": ["48px", {"lineHeight": "56px", "fontWeight": "700"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
